# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, help_text=b'The date of the registration')),
                ('birth_date', models.DateTimeField(auto_now_add=True, help_text=b'The date of birth')),
                ('gender', models.IntegerField(default=0)),
                ('weightInKg', models.IntegerField(default=70)),
                ('heightInCm', models.IntegerField(default=180)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
