# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalactivity',
            name='code',
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
