# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usda', '0002_auto_20161016_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ndbno',
            field=models.IntegerField(default=0),
        ),
    ]
