from django.db import transaction
from django.db import models


class PhysicalActivity(models.Model):
    id = models.IntegerField(primary_key=True)
    METS = models.FloatField()
    name = models.TextField(max_length=255)
    def __str__(self):
        return "PhysicalActivity (" + self.name + " " + str(self.METS) + ")"

    

@transaction.atomic
def add_items():
    PhysicalActivity(id=1003, name= "bicycling, mountain, uphill, vigorous", METS= 14.0).save()
    PhysicalActivity(id=1004, name= "bicycling, mountain, competitive, racing", METS= 16.0).save()
    PhysicalActivity(id=1008, name= "bicycling, BMX", METS= 8.5).save()
    PhysicalActivity(id=1009, name= "bicycling, mountain, general", METS= 8.5).save()
    PhysicalActivity(id=1010, name= "bicycling, <10 mph, leisure, to work or for pleasure (Taylor Code 115)", METS= 4.0).save()
    PhysicalActivity(id=1011, name= "bicycling, to/from work, self selected pace", METS= 6.8).save()
    PhysicalActivity(id=1013, name= "bicycling, on dirt or farm road, moderate pace", METS= 5.8).save()
    PhysicalActivity(id=1015, name= "bicycling, general", METS= 7.5).save()
    PhysicalActivity(id=1018, name= "bicycling, leisure, 5.5 mph", METS= 3.5).save()
    PhysicalActivity(id=1019, name= "bicycling, leisure, 9.4 mph", METS= 5.8).save()
    PhysicalActivity(id=1020, name= "bicycling, 10-11.9 mph, leisure, slow, light effort", METS= 6.8).save()
    PhysicalActivity(id=1030, name= "bicycling, 12-13.9 mph, leisure, moderate effort", METS= 8.0).save()
    PhysicalActivity(id=1040, name= "bicycling, 14-15.9 mph, racing or leisure, fast, vigorous effort", METS= 10.0).save()
    PhysicalActivity(id=1050, name= "bicycling, 16-19 mph, racing/not drafting or > 19 mph drafting, very fast, racing general", METS= 12.0).save()
    PhysicalActivity(id=1060, name= "bicycling, > 20 mph, racing, not drafting", METS= 15.8).save()
    PhysicalActivity(id=1065, name= "bicycling, 12 mph, seated, hands on brake hoods or bar drops, 80 rpm", METS= 8.5).save()
    PhysicalActivity(id=1066, name= "bicycling, 12 mph, standing, hands on brake hoods, 60 rpm", METS= 9.0).save()
    PhysicalActivity(id=1070, name= "unicycling", METS= 5.0).save()
    PhysicalActivity(id=2001, name= "activity promoting video game (e.g., Wii Fit), light effort (e.g., balance, yoga)", METS= 2.3).save()
    PhysicalActivity(id=2003, name= "activity promoting video game (e.g., Wii Fit), moderate effort (e.g., aerobic, resistance)", METS= 3.8).save()
    PhysicalActivity(id=2005, name= "activity promoting video/arcade game (e.g., Exergaming, Dance Dance Revolution), vigorous effort", METS= 7.2).save()
    PhysicalActivity(id=2008, name= "army type obstacle course exercise, boot camp training program", METS= 5.0).save()
    PhysicalActivity(id=2010, name= "bicycling, stationary, general", METS= 7.0).save()
    PhysicalActivity(id=2011, name= "bicycling, stationary, 30-50 watts, very light to light effort", METS= 3.5).save()
    PhysicalActivity(id=2012, name= "bicycling, stationary, 90-100 watts, moderate to vigorous effort", METS= 6.8).save()
    PhysicalActivity(id=2013, name= "bicycling, stationary, 101-160 watts, vigorous effort", METS= 8.8).save()
    PhysicalActivity(id=2014, name= "bicycling, stationary, 161-200 watts, vigorous effort", METS= 11.0).save()
    PhysicalActivity(id=2015, name= "bicycling, stationary, 201-270 watts, very vigorous effort", METS= 14.0).save()
    PhysicalActivity(id=2017, name= "bicycling, stationary, 51-89 watts, light-to-moderate effort", METS= 4.8).save()
    PhysicalActivity(id=2019, name= "bicycling, stationary, RPM/Spin bike class", METS= 8.5).save()
    PhysicalActivity(id=2020, name= "calisthenics (e.g., push ups, sit ups, pull-ups, jumping jacks), vigorous effort", METS= 8.0).save()
    PhysicalActivity(id=2022, name= "calisthenics (e.g., push ups, sit ups, pull-ups, lunges), moderate effort", METS= 3.8).save()
    PhysicalActivity(id=2024, name= "calisthenics (e.g., situps, abdominal crunches), light effort", METS= 2.8).save()
    PhysicalActivity(id=2030, name= "calisthenics, light or moderate effort, general (e.g., back exercises), going up & down from floor (Taylor Code 150)", METS= 3.5).save()
    PhysicalActivity(id=2035, name= "circuit training, moderate effort", METS= 4.3).save()
    PhysicalActivity(id=2040, name= "circuit training, including kettlebells, some aerobic movement with minimal rest, general, vigorous intensity", METS= 8.0).save()
    PhysicalActivity(id=2045, name= "CurvesTM exercise routines in women", METS= 3.5).save()
    PhysicalActivity(id=2048, name= "Elliptical trainer, moderate effort", METS= 5.0).save()
    PhysicalActivity(id=2050, name= "resistance training (weight lifting, free weight, nautilus or universal), power lifting or body building, vigorous effort (Taylor Code 210)", METS= 6.0).save()
    PhysicalActivity(id=2052, name= "resistance (weight) training, squats , slow or explosive effort", METS= 5.0).save()
    PhysicalActivity(id=2054, name= "resistance (weight) training, multiple exercises, 8-15 repetitions at varied resistance", METS= 3.5).save()
    PhysicalActivity(id=2060, name= "health club exercise, general (Taylor Code 160)", METS= 5.5).save()
    PhysicalActivity(id=2061, name= "health club exercise classes, general, gym/weight training combined in one visit", METS= 5.0).save()
    PhysicalActivity(id=2062, name= "health club exercise, conditioning classes", METS= 7.8).save()
    PhysicalActivity(id=2064, name= "home exercise, general", METS= 3.8).save()
    PhysicalActivity(id=2065, name= "stair-treadmill ergometer, general", METS= 9.0).save()
    PhysicalActivity(id=2068, name= "rope skipping, general", METS= 12.3).save()
    PhysicalActivity(id=2070, name= "rowing, stationary ergometer, general, vigorous effort", METS= 6.0).save()
    PhysicalActivity(id=2071, name= "rowing, stationary, general, moderate effort", METS= 4.8).save()
    PhysicalActivity(id=2072, name= "rowing, stationary, 100 watts, moderate effort", METS= 7.0).save()
    PhysicalActivity(id=2073, name= "rowing, stationary, 150 watts, vigorous effort", METS= 8.5).save()
    PhysicalActivity(id=2074, name= "rowing, stationary, 200 watts, very vigorous effort", METS= 12.0).save()
    PhysicalActivity(id=2080, name= "ski machine, general", METS= 6.8).save()
    PhysicalActivity(id=2085, name= "slide board exercise, general", METS= 11.0).save()
    PhysicalActivity(id=2090, name= "slimnastics, jazzercise", METS= 6.0).save()
    PhysicalActivity(id=2101, name= "stretching, mild", METS= 2.3).save()
    PhysicalActivity(id=2105, name= "pilates, general", METS= 3.0).save()
    PhysicalActivity(id=2110, name= "teaching exercise class (e.g., aerobic, water)", METS= 6.8).save()
    PhysicalActivity(id=2112, name= "therapeutic exercise ball, Fitball exercise", METS= 2.8).save()
    PhysicalActivity(id=2115, name= "upper body exercise, arm ergometer", METS= 2.8).save()
    PhysicalActivity(id=2117, name= "upper body exercise, stationary bicycle - Airdyne (arms only) 40 rpm, moderate", METS= 4.3).save()
    PhysicalActivity(id=2120, name= "water aerobics, water calisthenics, water exercise", METS= 5.3).save()
    PhysicalActivity(id=2135, name= "whirlpool, sitting", METS= 1.3).save()
    PhysicalActivity(id=2140, name= "video exercise workouts, TV conditioning programs (e.g., yoga, stretching), light effort", METS= 2.3).save()
    PhysicalActivity(id=2143, name= "video exercise workouts, TV conditioning programs (e.g., cardio-resistance), moderate effort", METS= 4.0).save()
    PhysicalActivity(id=2146, name= "video exercise workouts, TV conditioning programs (e.g., cardio-resistance), vigorous effort", METS= 6.0).save()
    PhysicalActivity(id=2150, name= "yoga, Hatha", METS= 2.5).save()
    PhysicalActivity(id=2160, name= "yoga, Power", METS= 4.0).save()
    PhysicalActivity(id=2170, name= "yoga, Nadisodhana", METS= 2.0).save()
    PhysicalActivity(id=2180, name= "yoga, Surya Namaskar", METS= 3.3).save()
    PhysicalActivity(id=2200, name= "native New Zealander physical activities (e.g., Haka Powhiri, Moteatea, Waita Tira, Whakawatea, etc.), general, moderate effort", METS= 5.3).save()
    PhysicalActivity(id=2205, name= "native New Zealander physical activities (e.g., Haka, Taiahab), general, vigorous effort", METS= 6.8).save()
    PhysicalActivity(id=3010, name= "ballet, modern, or jazz, general, rehearsal or class", METS= 5.0).save()
    PhysicalActivity(id=3012, name= "ballet, modern, or jazz, performance, vigorous effort", METS= 6.8).save()
    PhysicalActivity(id=3014, name= "tap", METS= 4.8).save()
    PhysicalActivity(id=3015, name= "aerobic, general", METS= 7.3).save()
    PhysicalActivity(id=3016, name= "aerobic, step, with 6 - 8 inch step", METS= 7.5).save()
    PhysicalActivity(id=3017, name= "aerobic, step, with 10 - 12 inch step", METS= 9.5).save()
    PhysicalActivity(id=3018, name= "aerobic, step, with 4-inch step", METS= 5.5).save()
    PhysicalActivity(id=3019, name= "bench step class, general", METS= 8.5).save()
    PhysicalActivity(id=3020, name= "aerobic, low impact", METS= 5.0).save()
    PhysicalActivity(id=3021, name= "aerobic, high impact", METS= 7.3).save()
    PhysicalActivity(id=3022, name= "aerobic dance wearing 10-15 lb weights", METS= 10.0).save()
    PhysicalActivity(id=3025, name= "ethnic or cultural dancing (e.g., Greek, Middle Eastern, hula, salsa, merengue, bamba y plena, flamenco, belly, and swing)", METS= 4.5).save()
    PhysicalActivity(id=3030, name= "ballroom, fast (Taylor Code 125)", METS= 5.5).save()
    PhysicalActivity(id=3031, name= "general dancing (e.g., disco, folk, Irish step dancing, line dancing, polka, contra, country)", METS= 7.8).save()
    PhysicalActivity(id=3038, name= "ballroom dancing, competitive, general", METS= 11.3).save()
    PhysicalActivity(id=3040, name= "ballroom, slow (e.g., waltz, foxtrot, slow dancing, samba, tango, 19th century dance, mambo, cha cha)", METS= 3.0).save()
    PhysicalActivity(id=3050, name= "Anishinaabe Jingle Dancing", METS= 5.5).save()
    PhysicalActivity(id=3060, name= "Caribbean dance (Abakua, Beguine, Bellair, Bongo, Brukins, Caribbean Quadrills, Dinki Mini, Gere, Gumbay, Ibo, Jonkonnu, Kumina, Oreisha, Jambu)", METS= 3.5).save()
    PhysicalActivity(id=4001, name= "fishing, general", METS= 3.5).save()
    PhysicalActivity(id=4005, name= "fishing, crab fishing", METS= 4.5).save()
    PhysicalActivity(id=4007, name= "fishing, catching fish with hands", METS= 4.0).save()
    PhysicalActivity(id=4010, name= "fishing related, digging worms, with shovel", METS= 4.3).save()
    PhysicalActivity(id=4020, name= "fishing from river bank and walking", METS= 4.0).save()
    PhysicalActivity(id=4030, name= "fishing from boat or canoe, sitting", METS= 2.0).save()
    PhysicalActivity(id=4040, name= "fishing from river bank, standing (Taylor Code 660)", METS= 3.5).save()
    PhysicalActivity(id=4050, name= "fishing in stream, in waders (Taylor Code 670)", METS= 6.0).save()
    PhysicalActivity(id=4060, name= "fishing, ice, sitting", METS= 2.0).save()
    PhysicalActivity(id=4061, name= "fishing, jog or line, standing, general", METS= 1.8).save()
    PhysicalActivity(id=4062, name= "fishing, dip net, setting net and retrieving fish, general", METS= 3.5).save()
    PhysicalActivity(id=4063, name= "fishing, set net, setting net and retrieving fish, general", METS= 3.8).save()
    PhysicalActivity(id=4064, name= "fishing, fishing wheel, setting net and retrieving fish, general", METS= 3.0).save()
    PhysicalActivity(id=4065, name= "fishing with a spear, standing", METS= 2.3).save()
    PhysicalActivity(id=4070, name= "hunting, bow and arrow, or crossbow", METS= 2.5).save()
    PhysicalActivity(id=4080, name= "hunting, deer, elk, large game (Taylor Code 170)", METS= 6.0).save()
    PhysicalActivity(id=4081, name= "hunting large game, dragging carcass", METS= 11.3).save()
    PhysicalActivity(id=4083, name= "hunting large marine animals", METS= 4.0).save()
    PhysicalActivity(id=4085, name= "hunting large game, from a hunting stand, limited walking", METS= 2.5).save()
    PhysicalActivity(id=4086, name= "hunting large game from a car, plane, or boat", METS= 2.0).save()
    PhysicalActivity(id=4090, name= "hunting, duck, wading", METS= 2.5).save()
    PhysicalActivity(id=4095, name= "hunting, flying fox, squirrel", METS= 3.0).save()
    PhysicalActivity(id=4100, name= "hunting, general", METS= 5.0).save()
    PhysicalActivity(id=4110, name= "hunting, pheasants or grouse (Taylor Code 680)", METS= 6.0).save()
    PhysicalActivity(id=4115, name= "hunting, birds", METS= 3.3).save()
    PhysicalActivity(id=4120, name= "hunting, rabbit, squirrel, prairie chick, raccoon, small game (Taylor Code 690)", METS= 5.0).save()
    PhysicalActivity(id=4123, name= "hunting, pigs, wild", METS= 3.3).save()
    PhysicalActivity(id=4124, name= "trapping game, general", METS= 2.0).save()
    PhysicalActivity(id=4125, name= "hunting, hiking with hunting gear", METS= 9.5).save()
    PhysicalActivity(id=4130, name= "pistol shooting or trap shooting, standing", METS= 2.5).save()
    PhysicalActivity(id=4140, name= "rifle exercises, shooting, lying down", METS= 2.3).save()
    PhysicalActivity(id=4145, name= "rifle exercises, shooting, kneeling or standing", METS= 2.5).save()
    PhysicalActivity(id=5010, name= "cleaning, sweeping carpet or floors, general", METS= 3.3).save()
    PhysicalActivity(id=5011, name= "cleaning, sweeping, slow, light effort", METS= 2.3).save()
    PhysicalActivity(id=5012, name= "cleaning, sweeping, slow, moderate effort", METS= 3.8).save()
    PhysicalActivity(id=5020, name= "cleaning, heavy or major (e.g. wash car, wash windows, clean garage), moderate effort", METS= 3.5).save()
    PhysicalActivity(id=5021, name= "cleaning, mopping, standing, moderate effort", METS= 3.5).save()
    PhysicalActivity(id=5022, name= "cleaning windows, washing windows, general", METS= 3.2).save()
    PhysicalActivity(id=5023, name= "mopping, standing, light effort", METS= 2.5).save()
    PhysicalActivity(id=5024, name= "polishing floors, standing, walking slowly, using electric polishing machine", METS= 4.5).save()
    PhysicalActivity(id=5025, name= "multiple household tasks all at once, light effort", METS= 2.8).save()
    PhysicalActivity(id=5026, name= "multiple household tasks all at once, moderate effort", METS= 3.5).save()
    PhysicalActivity(id=5027, name= "multiple household tasks all at once, vigorous effort", METS= 4.3).save()
    PhysicalActivity(id=5030, name= "cleaning, house or cabin, general, moderate effort", METS= 3.3).save()
    PhysicalActivity(id=5032, name= "dusting or polishing furniture, general", METS= 2.3).save()
    PhysicalActivity(id=5035, name= "kitchen activity, general, (e.g., cooking, washing dishes, cleaning up), moderate effort", METS= 3.3).save()
    PhysicalActivity(id=5040, name= "cleaning, general (straightening up, changing linen, carrying out trash, light effort", METS= 2.5).save()
    PhysicalActivity(id=5041, name= "wash dishes, standing or in general (not broken into stand/walk components)", METS= 1.8).save()
    PhysicalActivity(id=5042, name= "wash dishes, clearing dishes from table, walking, light effort", METS= 2.5).save()
    PhysicalActivity(id=5043, name= "vacuuming, general, moderate effort", METS= 3.3).save()
    PhysicalActivity(id=5044, name= "butchering animals, small", METS= 3.0).save()
    PhysicalActivity(id=5045, name= "butchering animal, large, vigorous effort", METS= 6.0).save()
    PhysicalActivity(id=5046, name= "cutting and smoking fish, drying fish or meat", METS= 2.3).save()
    PhysicalActivity(id=5048, name= "tanning hides, general", METS= 4.0).save()
    PhysicalActivity(id=5049, name= "cooking or food preparation, moderate effort", METS= 3.5).save()
    PhysicalActivity(id=5050, name= "cooking or food preparation - standing or sitting or in general (not broken into stand/walk components), manual appliances, light effort", METS= 2.0).save()
    PhysicalActivity(id=5051, name= "serving food, setting table, implied walking or standing", METS= 2.5).save()
    PhysicalActivity(id=5052, name= "cooking or food preparation, walking", METS= 2.5).save()
    PhysicalActivity(id=5053, name= "feeding household animals", METS= 2.5).save()
    PhysicalActivity(id=5055, name= "putting away groceries (e.g. carrying groceries, shopping without a grocery cart), carrying packages", METS= 2.5).save()
    PhysicalActivity(id=5056, name= "carrying groceries upstairs", METS= 7.5).save()
    PhysicalActivity(id=5057, name= "cooking Indian bread on an outside stove", METS= 3.0).save()
    PhysicalActivity(id=5060, name= "food shopping with or without a grocery cart, standing or walking", METS= 2.3).save()
    PhysicalActivity(id=5065, name= "non-food shopping, with or without a cart, standing or walking", METS= 2.3).save()
    PhysicalActivity(id=5070, name= "ironing", METS= 1.8).save()
    PhysicalActivity(id=5080, name= "knitting, sewing, light effort, wrapping presents, sitting", METS= 1.3).save()
    PhysicalActivity(id=5082, name= "sewing with a machine", METS= 2.8).save()
    PhysicalActivity(id=5090, name= "laundry, fold or hang clothes, put clothes in washer or dryer, packing suitcase, washing clothes by hand, implied standing, light effort", METS= 2.0).save()
    PhysicalActivity(id=5092, name= "laundry, hanging wash, washing clothes by hand, moderate effort", METS= 4.0).save()
    PhysicalActivity(id=5095, name= "laundry, putting away clothes, gathering clothes to pack, putting away laundry, implied walking", METS= 2.3).save()
    PhysicalActivity(id=5100, name= "making bed, changing linens", METS= 3.3).save()
    PhysicalActivity(id=5110, name= "maple syruping/sugar bushing (including carrying buckets, carrying wood)", METS= 5.0).save()
    PhysicalActivity(id=5120, name= "moving furniture, household items, carrying boxes", METS= 5.8).save()
    PhysicalActivity(id=5121, name= "moving, lifting light loads", METS= 5.0).save()
    PhysicalActivity(id=5125, name= "organizing room", METS= 4.8).save()
    PhysicalActivity(id=5130, name= "scrubbing floors, on hands and knees, scrubbing bathroom, bathtub, moderate effort", METS= 3.5).save()
    PhysicalActivity(id=5131, name= "scrubbing floors, on hands and knees, scrubbing bathroom, bathtub, light effort", METS= 2.0).save()
    PhysicalActivity(id=5132, name= "scrubbing floors, on hands and knees, scrubbing bathroom, bathtub, vigorous effort", METS= 6.5).save()
    PhysicalActivity(id=5140, name= "sweeping garage, sidewalk or outside of house", METS= 4.0).save()
    PhysicalActivity(id=5146, name= "standing, packing/unpacking boxes, occasional lifting of lightweight household items, loading or unloading items in car, moderate effort", METS= 3.5).save()
    PhysicalActivity(id=5147, name= "implied walking, putting away household items, moderate effort", METS= 3.0).save()
    PhysicalActivity(id=5148, name= "watering plants", METS= 2.5).save()
    PhysicalActivity(id=5149, name= "building a fire inside", METS= 2.5).save()
    PhysicalActivity(id=5150, name= "moving household items upstairs, carrying boxes or furniture", METS= 9.0).save()
    PhysicalActivity(id=5160, name= "standing, light effort tasks (pump gas, change light bulb, etc.)", METS= 2.0).save()
    PhysicalActivity(id=5165, name= "walking, moderate effort tasks, non-cleaning (readying to leave, shut/lock doors, close windows, etc.)", METS= 3.5).save()
    PhysicalActivity(id=5170, name= "sitting, playing with child(ren), light effort, only active periods", METS= 2.2).save()
    PhysicalActivity(id=5171, name= "standing, playing with child(ren) light effort, only active periods", METS= 2.8).save()
    PhysicalActivity(id=5175, name= "walking/running, playing with child(ren), moderate effort, only active periods", METS= 3.5).save()
    PhysicalActivity(id=5180, name= "walking/running, playing with child(ren), vigorous effort, only active periods", METS= 5.8).save()
    PhysicalActivity(id=5181, name= "walking and carrying small child, child weighing 15 lbs or more", METS= 3.0).save()
    PhysicalActivity(id=5182, name= "walking and carrying small child, child weighing less than 15 lbs", METS= 2.3).save()
    PhysicalActivity(id=5183, name= "standing, holding child", METS= 2.0).save()
    PhysicalActivity(id=5184, name= "child care, infant, general", METS= 2.5).save()
    PhysicalActivity(id=5185, name= "child care, sitting/kneeling (e.g., dressing, bathing, grooming, feeding, occasional lifting of child), light effort, general", METS= 2.0).save()
    PhysicalActivity(id=5186, name= "child care, standing (e.g., dressing, bathing, grooming, feeding, occasional lifting of child), moderate effort", METS= 3.0).save()
    PhysicalActivity(id=5188, name= "reclining with baby", METS= 1.5).save()
    PhysicalActivity(id=5189, name= "breastfeeding, sitting or reclining", METS= 2.0).save()
    PhysicalActivity(id=5190, name= "sit, playing with animals, light effort, only active periods", METS= 2.5).save()
    PhysicalActivity(id=5191, name= "stand, playing with animals, light effort, only active periods", METS= 2.8).save()
    PhysicalActivity(id=5192, name= "walk/run, playing with animals, general, light effort, only active periods", METS= 3.0).save()
    PhysicalActivity(id=5193, name= "walk/run, playing with animals, moderate effort, only active periods", METS= 4.0).save()
    PhysicalActivity(id=5194, name= "walk/run, playing with animals, vigorous effort, only active periods", METS= 5.0).save()
    PhysicalActivity(id=5195, name= "standing, bathing dog", METS= 3.5).save()
    PhysicalActivity(id=5197, name= "animal care, household animals, general", METS= 2.3).save()
    PhysicalActivity(id=5200, name= "elder care, disabled adult, bathing, dressing, moving into and out of bed, only active periods", METS= 4.0).save()
    PhysicalActivity(id=5205, name= "elder care, disabled adult, feeding, combing hair, light effort, only active periods", METS= 2.3).save()
    PhysicalActivity(id=6010, name= "airplane repair", METS= 3.0).save()
    PhysicalActivity(id=6020, name= "automobile body work", METS= 4.0).save()
    PhysicalActivity(id=6030, name= "automobile repair, light or moderate effort", METS= 3.3).save()
    PhysicalActivity(id=6040, name= "carpentry, general, workshop (Taylor Code 620)", METS= 3.0).save()
    PhysicalActivity(id=6050, name= "carpentry, outside house, installing rain gutters (Taylor Code 640),carpentry, outside house, building a fence", METS= 6.0).save()
    PhysicalActivity(id=6052, name= "carpentry, outside house, building a fence", METS= 3.8).save()
    PhysicalActivity(id=6060, name= "carpentry, finishing or refinishing cabinets or furniture", METS= 3.3).save()
    PhysicalActivity(id=6070, name= "carpentry, sawing hardwood", METS= 6.0).save()
    PhysicalActivity(id=6072, name= "carpentry, home remodeling tasks, moderate effort", METS= 4.0).save()
    PhysicalActivity(id=6074, name= "carpentry, home remodeling tasks, light effort", METS= 2.3).save()
    PhysicalActivity(id=6080, name= "caulking, chinking log cabin", METS= 5.0).save()
    PhysicalActivity(id=6090, name= "caulking, except log cabin", METS= 4.5).save()
    PhysicalActivity(id=6100, name= "cleaning gutters", METS= 5.0).save()
    PhysicalActivity(id=6110, name= "excavating garage", METS= 5.0).save()
    PhysicalActivity(id=6120, name= "hanging storm windows", METS= 5.0).save()
    PhysicalActivity(id=6122, name= "hanging sheet rock inside house", METS= 5.0).save()
    PhysicalActivity(id=6124, name= "hammering nails", METS= 3.0).save()
    PhysicalActivity(id=6126, name= "home repair, general, light effort", METS= 2.5).save()
    PhysicalActivity(id=6127, name= "home repair, general, moderate effort", METS= 4.5).save()
    PhysicalActivity(id=6128, name= "home repair, general, vigorous effort", METS= 6.0).save()
    PhysicalActivity(id=6130, name= "laying or removing carpet", METS= 4.5).save()
    PhysicalActivity(id=6140, name= "laying tile or linoleum,repairing appliances", METS= 3.8).save()
    PhysicalActivity(id=6144, name= "repairing appliances", METS= 3.0).save()
    PhysicalActivity(id=6150, name= "painting, outside home (Taylor Code 650)", METS= 5.0).save()
    PhysicalActivity(id=6160, name= "painting inside house,wallpapering, scraping paint", METS= 3.3).save()
    PhysicalActivity(id=6165, name= "painting, (Taylor Code 630)", METS= 4.5).save()
    PhysicalActivity(id=6167, name= "plumbing, general", METS= 3.0).save()
    PhysicalActivity(id=6170, name= "put on and removal of tarp - sailboat", METS= 3.0).save()
    PhysicalActivity(id=6180, name= "roofing", METS= 6.0).save()
    PhysicalActivity(id=6190, name= "sanding floors with a power sander", METS= 4.5).save()
    PhysicalActivity(id=6200, name= "scraping and painting sailboat or powerboat", METS= 4.5).save()
    PhysicalActivity(id=6205, name= "sharpening tools", METS= 2.0).save()
    PhysicalActivity(id=6210, name= "spreading dirt with a shovel", METS= 5.0).save()
    PhysicalActivity(id=6220, name= "washing and waxing hull of sailboat or airplane", METS= 4.5).save()
    PhysicalActivity(id=6225, name= "washing and waxing car", METS= 2.0).save()
    PhysicalActivity(id=6230, name= "washing fence, painting fence, moderate effort", METS= 4.5).save()
    PhysicalActivity(id=6240, name= "wiring, tapping-splicing", METS= 3.3).save()
    PhysicalActivity(id=7010, name= "lying quietly and watching television", METS= 1.0).save()
    PhysicalActivity(id=7011, name= "lying quietly, doing nothing, lying in bed awake, listening to music (not talking or reading)", METS= 1.3).save()
    PhysicalActivity(id=7020, name= "sitting quietly and watching television", METS= 1.3).save()
    PhysicalActivity(id=7021, name= "sitting quietly, general", METS= 1.3).save()
    PhysicalActivity(id=7022, name= "sitting quietly, fidgeting, general, fidgeting hands", METS= 1.5).save()
    PhysicalActivity(id=7023, name= "sitting, fidgeting feet", METS= 1.8).save()
    PhysicalActivity(id=7024, name= "sitting, smoking", METS= 1.3).save()
    PhysicalActivity(id=7025, name= "sitting, listening to music (not talking or reading) or watching a movie in a theater", METS= 1.5).save()
    PhysicalActivity(id=7026, name= "sitting at a desk, resting head in hands", METS= 1.3).save()
    PhysicalActivity(id=7030, name= "sleeping", METS= 1.0).save()
    PhysicalActivity(id=7040, name= "standing quietly, standing in a line", METS= 1.3).save()
    PhysicalActivity(id=7041, name= "standing, fidgeting", METS= 1.8).save()
    PhysicalActivity(id=7050, name= "reclining, writing", METS= 1.3).save()
    PhysicalActivity(id=7060, name= "reclining, talking or talking on phone", METS= 1.3).save()
    PhysicalActivity(id=7070, name= "reclining, reading", METS= 1.3).save()
    PhysicalActivity(id=7075, name= "meditating", METS= 1.0).save()
    PhysicalActivity(id=8009, name= "carrying, loading or stacking wood, loading/unloading or carrying lumber, light-to-moderate effort", METS= 3.3).save()
    PhysicalActivity(id=8010, name= "carrying, loading or stacking wood, loading/unloading or carrying lumber", METS= 5.5).save()
    PhysicalActivity(id=8019, name= "chopping wood, splitting logs, moderate effort", METS= 4.5).save()
    PhysicalActivity(id=8020, name= "chopping wood, splitting logs, vigorous effort", METS= 6.3).save()
    PhysicalActivity(id=8025, name= "clearing light brush, thinning garden, moderate effort", METS= 3.5).save()
    PhysicalActivity(id=8030, name= "clearing brush/land, undergrowth, or ground, hauling branches, wheelbarrow chores, vigorous effort", METS= 6.3).save()
    PhysicalActivity(id=8040, name= "digging sandbox, shoveling sand", METS= 5.0).save()
    PhysicalActivity(id=8045, name= "digging, spading, filling garden, composting, light-to-moderate effort", METS= 3.5).save()
    PhysicalActivity(id=8050, name= "digging, spading, filling garden, compositing, (Taylor Code 590)", METS= 5.0).save()
    PhysicalActivity(id=8052, name= "digging, spading, filling garden, composting, vigorous effort", METS= 7.8).save()
    PhysicalActivity(id=8055, name= "driving tractor", METS= 2.8).save()
    PhysicalActivity(id=8057, name= "felling trees, large size", METS= 8.3).save()
    PhysicalActivity(id=8058, name= "felling trees, small-medium size", METS= 5.3).save()
    PhysicalActivity(id=8060, name= "gardening with heavy power tools, tilling a garden, chain saw", METS= 5.8).save()
    PhysicalActivity(id=8065, name= "gardening, using containers, older adults > 60 years", METS= 2.3).save()
    PhysicalActivity(id=8070, name= "irrigation channels, opening and closing ports", METS= 4.0).save()
    PhysicalActivity(id=8080, name= "laying crushed rock", METS= 6.3).save()
    PhysicalActivity(id=8090, name= "laying sod", METS= 5.0).save()
    PhysicalActivity(id=8095, name= "mowing lawn, general", METS= 5.5).save()
    PhysicalActivity(id=8100, name= "mowing lawn, riding mower (Taylor Code 550)", METS= 2.5).save()
    PhysicalActivity(id=8110, name= "mowing lawn, walk, hand mower (Taylor Code 570)", METS= 6.0).save()
    PhysicalActivity(id=8120, name= "mowing lawn, walk, power mower, moderate or vigorous effort", METS= 5.0).save()
    PhysicalActivity(id=8125, name= "mowing lawn, power mower, light or moderate effort (Taylor Code 590)", METS= 4.5).save()
    PhysicalActivity(id=8130, name= "operating snow blower, walking", METS= 2.5).save()
    PhysicalActivity(id=8135, name= "planting, potting, transplanting seedlings or plants, light effort", METS= 2.0).save()
    PhysicalActivity(id=8140, name= "planting seedlings, shrub, stooping, moderate effort", METS= 4.3).save()
    PhysicalActivity(id=8145, name= "planting crops or garden, stooping, moderate effort", METS= 4.3).save()
    PhysicalActivity(id=8150, name= "planting trees", METS= 4.5).save()
    PhysicalActivity(id=8160, name= "raking lawn or leaves, moderate effort", METS= 3.8).save()
    PhysicalActivity(id=8165, name= "raking lawn (Taylor Code 600)", METS= 4.0).save()
    PhysicalActivity(id=8170, name= "raking roof with snow rake", METS= 4.0).save()
    PhysicalActivity(id=8180, name= "riding snow blower", METS= 3.0).save()
    PhysicalActivity(id=8190, name= "sacking grass, leaves", METS= 4.0).save()
    PhysicalActivity(id=8192, name= "shoveling dirt or mud", METS= 5.5).save()
    PhysicalActivity(id=8195, name= "shoveling snow, by hand, moderate effort", METS= 5.3).save()
    PhysicalActivity(id=8200, name= "shovelling snow, by hand (Taylor Code 610)", METS= 6.0).save()
    PhysicalActivity(id=8202, name= "shoveling snow, by hand, vigorous effort", METS= 7.5).save()
    PhysicalActivity(id=8210, name= "trimming shrubs or trees, manual cutter", METS= 4.0).save()
    PhysicalActivity(id=8215, name= "trimming shrubs or trees, power cutter, using leaf blower, edge, moderate effort", METS= 3.5).save()
    PhysicalActivity(id=8220, name= "walking, applying fertilizer or seeding a lawn, push applicator", METS= 3.0).save()
    PhysicalActivity(id=8230, name= "watering lawn or garden, standing or walking", METS= 1.5).save()
    PhysicalActivity(id=8239, name= "weeding, cultivating garden, light-to-moderate effort", METS= 3.5).save()
    PhysicalActivity(id=8240, name= "weeding, cultivating garden (Taylor Code 580)", METS= 4.5).save()
    PhysicalActivity(id=8241, name= "weeding, cultivating garden, using a hoe, moderate-to-vigorous effort", METS= 5.0).save()
    PhysicalActivity(id=8245, name= "gardening, general, moderate effort", METS= 3.8).save()
    PhysicalActivity(id=8246, name= "picking fruit off trees, picking fruits/vegetables, moderate effort", METS= 3.5).save()
    PhysicalActivity(id=8248, name= "picking fruit off trees, gleaning fruits, picking fruits/vegetables, climbing ladder to pick fruit, vigorous effort", METS= 4.5).save()
    PhysicalActivity(id=8250, name= "implied walking/standing - picking up yard, light, picking flowers or vegetables", METS= 3.3).save()
    PhysicalActivity(id=8251, name= "walking, gathering gardening tools", METS= 3.0).save()
    PhysicalActivity(id=8255, name= "wheelbarrow, pushing garden cart or wheelbarrow", METS= 5.5).save()
    PhysicalActivity(id=8260, name= "yard work, general, light effort", METS= 3.0).save()
    PhysicalActivity(id=8261, name= "yard work, general, moderate effort", METS= 4.0).save()
    PhysicalActivity(id=8262, name= "yard work, general, vigorous effort", METS= 6.0).save()
    PhysicalActivity(id=9000, name= "board game playing, sitting", METS= 1.5).save()
    PhysicalActivity(id=9005, name= "casino gambling, standing", METS= 2.5).save()
    PhysicalActivity(id=9010, name= "card playing, sitting", METS= 1.5).save()
    PhysicalActivity(id=9013, name= "chess game, sitting", METS= 1.5).save()
    PhysicalActivity(id=9015, name= "copying documents, standing", METS= 1.5).save()
    PhysicalActivity(id=9020, name= "drawing, writing, painting, standing", METS= 1.8).save()
    PhysicalActivity(id=9025, name= "laughing, sitting", METS= 1.0).save()
    PhysicalActivity(id=9030, name= "sitting, reading, book, newspaper, etc.", METS= 1.3).save()
    PhysicalActivity(id=9040, name= "sitting, writing, desk work, typing", METS= 1.3).save()
    PhysicalActivity(id=9045, name= "sitting, playing traditional video game, computer game", METS= 1.0).save()
    PhysicalActivity(id=9050, name= "standing, talking in person, on the phone, computer, or text messaging, light effort", METS= 1.8).save()
    PhysicalActivity(id=9055, name= "sitting, talking in person, on the phone, computer, or text messaging, light effort", METS= 1.5).save()
    PhysicalActivity(id=9060, name= "sitting, studying, general, including reading and/or writing, light effort", METS= 1.3).save()
    PhysicalActivity(id=9065, name= "sitting, in class, general, including note-taking or class discussion", METS= 1.8).save()
    PhysicalActivity(id=9070, name= "standing, reading", METS= 1.8).save()
    PhysicalActivity(id=9071, name= "standing, miscellaneous", METS= 2.5).save()
    PhysicalActivity(id=9075, name= "sitting, arts and crafts, carving wood, weaving, spinning wool, light effort", METS= 1.8).save()
    PhysicalActivity(id=9080, name= "sitting, arts and crafts, carving wood, weaving, spinning wool, moderate effort", METS= 3.0).save()
    PhysicalActivity(id=9085, name= "standing, arts and crafts, sand painting, carving, weaving, light effort", METS= 2.5).save()
    PhysicalActivity(id=9090, name= "standing, arts and crafts, sand painting, carving, weaving, moderate effort", METS= 3.3).save()
    PhysicalActivity(id=9095, name= "standing, arts and crafts, sand painting, carving, weaving, vigorous effort", METS= 3.5).save()
    PhysicalActivity(id=9100, name= "retreat/family reunion activities involving sitting, relaxing, talking, eating", METS= 1.8).save()
    PhysicalActivity(id=9101, name= "retreat/family reunion activities involving playing games with children", METS= 3.0).save()
    PhysicalActivity(id=9105, name= "touring/traveling/vacation involving riding in a vehicle", METS= 2.0).save()
    PhysicalActivity(id=9106, name= "touring/traveling/vacation involving walking", METS= 3.5).save()
    PhysicalActivity(id=9110, name= "camping involving standing, walking, sitting, light-to-moderate effort", METS= 2.5).save()
    PhysicalActivity(id=9115, name= "sitting at a sporting event, spectator", METS= 1.5).save()
    PhysicalActivity(id=10010, name= "accordion, sitting", METS= 1.8).save()
    PhysicalActivity(id=10020, name= "cello, sitting", METS= 2.3).save()
    PhysicalActivity(id=10030, name= "conducting orchestra, standing", METS= 2.3).save()
    PhysicalActivity(id=10035, name= "double bass, standing", METS= 2.5).save()
    PhysicalActivity(id=10040, name= "drums, sitting", METS= 3.8).save()
    PhysicalActivity(id=10045, name= "drumming (e.g., bongo, conga, benbe), moderate, sitting", METS= 3.0).save()
    PhysicalActivity(id=10050, name= "flute, sitting", METS= 2.0).save()
    PhysicalActivity(id=10060, name= "horn, standing", METS= 1.8).save()
    PhysicalActivity(id=10070, name= "piano, sitting", METS= 2.3).save()
    PhysicalActivity(id=10074, name= "playing musical instruments, general", METS= 2.0).save()
    PhysicalActivity(id=10077, name= "organ, sitting", METS= 2.0).save()
    PhysicalActivity(id=10080, name= "trombone, standing", METS= 3.5).save()
    PhysicalActivity(id=10090, name= "trumpet, standing", METS= 1.8).save()
    PhysicalActivity(id=10100, name= "violin, sitting", METS= 2.5).save()
    PhysicalActivity(id=10110, name= "woodwind, sitting", METS= 1.8).save()
    PhysicalActivity(id=10120, name= "guitar, classical, folk, sitting", METS= 2.0).save()
    PhysicalActivity(id=10125, name= "guitar, rock and roll band, standing", METS= 3.0).save()
    PhysicalActivity(id=10130, name= "marching band, baton twirling, walking, moderate pace, general", METS= 4.0).save()
    PhysicalActivity(id=10131, name= "marching band, playing an instrument, walking, brisk pace, general", METS= 5.5).save()
    PhysicalActivity(id=10135, name= "marching band, drum major, walking", METS= 3.5).save()
    PhysicalActivity(id=11003, name= "active workstation, treadmill desk, walking", METS= 2.3).save()
    PhysicalActivity(id=11006, name= "airline flight attendant", METS= 3.0).save()
    PhysicalActivity(id=11010, name= "bakery, general, moderate effort", METS= 4.0).save()
    PhysicalActivity(id=11015, name= "bakery, light effort", METS= 2.0).save()
    PhysicalActivity(id=11020, name= "bookbinding", METS= 2.3).save()
    PhysicalActivity(id=11030, name= "building road, driving heavy machinery", METS= 6.0).save()
    PhysicalActivity(id=11035, name= "building road, directing traffic, standing", METS= 2.0).save()
    PhysicalActivity(id=11038, name= "carpentry, general, light effort", METS= 2.5).save()
    PhysicalActivity(id=11040, name= "carpentry, general, moderate effort", METS= 4.3).save()
    PhysicalActivity(id=11042, name= "carpentry, general, heavy or vigorous effort", METS= 7.0).save()
    PhysicalActivity(id=11050, name= "carrying heavy loads (e.g., bricks, tools)", METS= 8.0).save()
    PhysicalActivity(id=11060, name= "carrying moderate loads up stairs, moving boxes 25-49 lbs", METS= 8.0).save()
    PhysicalActivity(id=11070, name= "chambermaid, hotel housekeeper, making bed, cleaning bathroom, pushing cart", METS= 4.0).save()
    PhysicalActivity(id=11080, name= "coal mining, drilling coal, rock", METS= 5.3).save()
    PhysicalActivity(id=11090, name= "coal mining, erecting supports", METS= 5.0).save()
    PhysicalActivity(id=11100, name= "coal mining, general", METS= 5.5).save()
    PhysicalActivity(id=11110, name= "coal mining, shoveling coal", METS= 6.3).save()
    PhysicalActivity(id=11115, name= "cook, chef", METS= 2.5).save()
    PhysicalActivity(id=11120, name= "construction, outside, remodeling, new structures (e.g., roof repair, miscellaneous)", METS= 4.0).save()
    PhysicalActivity(id=11125, name= "custodial work, light effort (e.g., cleaning sink and toilet, dusting, vacuuming, light cleaning)", METS= 2.3).save()
    PhysicalActivity(id=11126, name= "custodial work, moderate effort (e.g., electric buffer, feathering arena floors, mopping, taking out trash, vacuuming)", METS= 3.8).save()
    PhysicalActivity(id=11130, name= "electrical work (e.g., hook up wire, tapping-splicing)", METS= 3.3).save()
    PhysicalActivity(id=11135, name= "engineer (e.g., mechanical or electrical)", METS= 1.8).save()
    PhysicalActivity(id=11145, name= "farming, vigorous effort (e.g., baling hay, cleaning barn)", METS= 7.8).save()
    PhysicalActivity(id=11146, name= "farming, moderate effort (e.g., feeding animals, chasing cattle by walking and/or horseback, spreading manure, harvesting crops)", METS= 4.8).save()
    PhysicalActivity(id=11147, name= "farming, light effort (e.g., cleaning animal sheds, preparing animal feed)", METS= 2.0).save()
    PhysicalActivity(id=11170, name= "farming, driving tasks (e.g., driving tractor or harvester)", METS= 2.8).save()
    PhysicalActivity(id=11180, name= "farming, feeding small animals", METS= 3.5).save()
    PhysicalActivity(id=11190, name= "farming, feeding cattle, horses", METS= 4.3).save()
    PhysicalActivity(id=11191, name= "farming, hauling water for animals, general hauling water,farming, general hauling water", METS= 4.3).save()
    PhysicalActivity(id=11192, name= "farming, taking care of animals (e.g., grooming, brushing, shearing sheep, assisting with birthing, medical care, branding), general", METS= 4.5).save()
    PhysicalActivity(id=11195, name= "farming, rice, planting, grain milling activities", METS= 3.8).save()
    PhysicalActivity(id=11210, name= "farming, milking by hand, cleaning pails, moderate effort", METS= 3.5).save()
    PhysicalActivity(id=11220, name= "farming, milking by machine, light effort", METS= 1.3).save()
    PhysicalActivity(id=11240, name= "fire fighter, general", METS= 8.0).save()
    PhysicalActivity(id=11244, name= "fire fighter, rescue victim, automobile accident, using pike pole", METS= 6.8).save()
    PhysicalActivity(id=11245, name= "fire fighter, raising and climbing ladder with full gear, simulated fire supression", METS= 8.0).save()
    PhysicalActivity(id=11246, name= "fire fighter, hauling hoses on ground, carrying/hoisting equipment, breaking down walls etc., wearing full gear", METS= 9.0).save()
    PhysicalActivity(id=11247, name= "fishing, commercial, light effort", METS= 3.5).save()
    PhysicalActivity(id=11248, name= "fishing, commercial, moderate effort", METS= 5.0).save()
    PhysicalActivity(id=11249, name= "fishing, commercial, vigorous effort", METS= 7.0).save()
    PhysicalActivity(id=11250, name= "forestry, ax chopping, very fast, 1.25 kg axe, 51 blows/min, extremely vigorous effort", METS= 17.5).save()
    PhysicalActivity(id=11260, name= "forestry, ax chopping, slow, 1.25 kg axe, 19 blows/min, moderate effort", METS= 5.0).save()
    PhysicalActivity(id=11262, name= "forestry, ax chopping, fast, 1.25 kg axe, 35 blows/min, vigorous effort", METS= 8.0).save()
    PhysicalActivity(id=11264, name= "forestry, moderate effort (e.g., sawing wood with power saw, weeding, hoeing)", METS= 4.5).save()
    PhysicalActivity(id=11266, name= "forestry, vigorous effort (e.g., barking, felling, or trimming trees, carrying or stacking logs, planting seeds, sawing lumber by hand)", METS= 8.0).save()
    PhysicalActivity(id=11370, name= "furriery", METS= 4.5).save()
    PhysicalActivity(id=11375, name= "garbage collector, walking, dumping bins into truck", METS= 4.0).save()
    PhysicalActivity(id=11378, name= "hairstylist (e.g., plaiting hair, manicure, make-up artist)", METS= 1.8).save()
    PhysicalActivity(id=11380, name= "horse grooming, including feeding, cleaning stalls, bathing, brushing, clipping, longeing and exercising horses", METS= 7.3).save()
    PhysicalActivity(id=11381, name= "horse, feeding, watering, cleaning stalls, implied walking and lifting loads", METS= 4.3).save()
    PhysicalActivity(id=11390, name= "horse racing, galloping", METS= 7.3).save()
    PhysicalActivity(id=11400, name= "horse racing, trotting", METS= 5.8).save()
    PhysicalActivity(id=11410, name= "horse racing, walking", METS= 3.8).save()
    PhysicalActivity(id=11413, name= "kitchen maid", METS= 3.0).save()
    PhysicalActivity(id=11415, name= "lawn keeper, yard work, general", METS= 4.0).save()
    PhysicalActivity(id=11418, name= "laundry worker", METS= 3.3).save()
    PhysicalActivity(id=11420, name= "locksmith", METS= 3.0).save()
    PhysicalActivity(id=11430, name= "machine tooling (e.g., machining, working sheet metal, machine fitter, operating lathe, welding) light-to-moderate effort", METS= 3.0).save()
    PhysicalActivity(id=11450, name= "Machine tooling, operating punch press, moderate effort", METS= 5.0).save()
    PhysicalActivity(id=11472, name= "manager, property", METS= 1.8).save()
    PhysicalActivity(id=11475, name= "manual or unskilled labor, general, light effort", METS= 2.8).save()
    PhysicalActivity(id=11476, name= "manual or unskilled labor, general, moderate effort", METS= 4.5).save()
    PhysicalActivity(id=11477, name= "manual or unskilled labor, general, vigorous effort", METS= 6.5).save()
    PhysicalActivity(id=11480, name= "masonry, concrete, moderate effort", METS= 4.3).save()
    PhysicalActivity(id=11482, name= "masonry, concrete, light effort", METS= 2.5).save()
    PhysicalActivity(id=11485, name= "massage therapist, standing", METS= 4.0).save()
    PhysicalActivity(id=11490, name= "moving, carrying or pushing heavy objects, 75 lbs or more, only active time (e.g., desks, moving van work)", METS= 7.5).save()
    PhysicalActivity(id=11495, name= "skindiving or SCUBA diving as a frogman, Navy Seal", METS= 12.0).save()
    PhysicalActivity(id=11500, name= "operating heavy duty equipment, automated, not driving", METS= 2.5).save()
    PhysicalActivity(id=11510, name= "orange grove work, picking fruit", METS= 4.5).save()
    PhysicalActivity(id=11514, name= "painting,house, furniture, moderate effort", METS= 3.3).save()
    PhysicalActivity(id=11516, name= "plumbing activities", METS= 3.0).save()
    PhysicalActivity(id=11520, name= "printing, paper industry worker, standing", METS= 2.0).save()
    PhysicalActivity(id=11525, name= "police, directing traffic, standing", METS= 2.5).save()
    PhysicalActivity(id=11526, name= "police, driving a squad car, sitting", METS= 2.5).save()
    PhysicalActivity(id=11527, name= "police, riding in a squad car, sitting", METS= 1.3).save()
    PhysicalActivity(id=11528, name= "police, making an arrest, standing", METS= 4.0).save()
    PhysicalActivity(id=11529, name= "postal carrier, walking to deliver mail", METS= 2.3).save()
    PhysicalActivity(id=11530, name= "shoe repair, general", METS= 2.0).save()
    PhysicalActivity(id=11540, name= "shoveling, digging ditches", METS= 7.8).save()
    PhysicalActivity(id=11550, name= "shoveling, more than 16 lbs/minute, deep digging, vigorous effort", METS= 8.8).save()
    PhysicalActivity(id=11560, name= "shoveling, less than 10 lbs/minute, moderate effort", METS= 5.0).save()
    PhysicalActivity(id=11570, name= "shoveling, 10 to 15 lbs/minute, vigorous effort", METS= 6.5).save()
    PhysicalActivity(id=11580, name= "sitting tasks, light effort (e.g., office work, chemistry lab work, computer work, light assembly repair, watch repair, reading, desk work)", METS= 1.5).save()
    PhysicalActivity(id=11585, name= "sitting meetings, light effort, general, and/or with talking involved (e.g., eating at a business meeting)", METS= 1.5).save()
    PhysicalActivity(id=11590, name= "sitting tasks, moderate effort (e.g., pushing heavy levers, riding mower/forklift, crane operation)", METS= 2.5).save()
    PhysicalActivity(id=11593, name= "sitting, teaching stretching or yoga, or light effort exercise class", METS= 2.8).save()
    PhysicalActivity(id=11600, name= "standing tasks, light effort (e.g., bartending, store clerk, assembling, filing, duplicating, librarian, putting up a Christmas tree, standing and talking at work, changing clothes when teaching physical education, standing)", METS= 3.0).save()
    PhysicalActivity(id=11610, name= "standing, light/moderate effort (e.g., assemble/repair heavy parts, welding,stocking parts,auto repair,standing, packing boxes, nursing patient care)", METS= 3.0).save()
    PhysicalActivity(id=11615, name= "standing, moderate effort, lifting items continuously, 10 \u2013 20 lbs, with limited walking or resting", METS= 4.5).save()
    PhysicalActivity(id=11620, name= "standing, moderate effort, intermittent lifting 50 lbs, hitch/twisting ropes", METS= 3.5).save()
    PhysicalActivity(id=11630, name= "standing, moderate/heavy tasks (e.g., lifting more than 50 lbs, masonry, painting, paper hanging)", METS= 4.5).save()
    PhysicalActivity(id=11708, name= "steel mill, moderate effort (e.g., fettling, forging, tipping molds)", METS= 5.3).save()
    PhysicalActivity(id=11710, name= "steel mill, vigorous effort (e.g., hand rolling, merchant mill rolling, removing slag, tending furnace)", METS= 8.3).save()
    PhysicalActivity(id=11720, name= "tailoring, cutting fabric", METS= 2.3).save()
    PhysicalActivity(id=11730, name= "tailoring, general", METS= 2.5).save()
    PhysicalActivity(id=11740, name= "tailoring, hand sewing", METS= 1.8).save()
    PhysicalActivity(id=11750, name= "tailoring, machine sewing", METS= 2.5).save()
    PhysicalActivity(id=11760, name= "tailoring, pressing", METS= 3.5).save()
    PhysicalActivity(id=11763, name= "tailoring, weaving, light effort (e.g., finishing operations, washing, dyeing, inspecting cloth, counting yards, paperwork)", METS= 2.0).save()
    PhysicalActivity(id=11765, name= "tailoring, weaving, moderate effort (e.g., spinning and weaving operations, delivering boxes of yam to spinners, loading of warp bean, pinwinding, conewinding, warping, cloth cutting)", METS= 4.0).save()
    PhysicalActivity(id=11766, name= "truck driving, loading and unloading truck, tying down load, standing, walking and carrying heavy loads", METS= 6.5).save()
    PhysicalActivity(id=11767, name= "Truch, driving delivery truck, taxi, shuttlebus, school bus", METS= 2.0).save()
    PhysicalActivity(id=11770, name= "typing, electric, manual or computer", METS= 1.3).save()
    PhysicalActivity(id=11780, name= "using heavy power tools such as pneumatic tools (e.g., jackhammers, drills)", METS= 6.3).save()
    PhysicalActivity(id=11790, name= "using heavy tools (not power) such as shovel, pick, tunnel bar, spade", METS= 8.0).save()
    PhysicalActivity(id=11791, name= "walking on job, less than 2.0 mph, very slow speed, in office or lab area", METS= 2.0).save()
    PhysicalActivity(id=11792, name= "walking on job, 3.0 mph, in office, moderate speed, not carrying anything", METS= 3.5).save()
    PhysicalActivity(id=11793, name= "walking on job, 3.5 mph, in office, brisk speed, not carrying anything", METS= 4.3).save()
    PhysicalActivity(id=11795, name= "walking on job, 2.5 mph, slow speed and carrying light objects less than 25 lbs", METS= 3.5).save()
    PhysicalActivity(id=11796, name= "walking, gathering things at work, ready to leave", METS= 3.0).save()
    PhysicalActivity(id=11797, name= "walking, 2.5 mph, slow speed, carrying heavy objects more than 25 lbs", METS= 3.8).save()
    PhysicalActivity(id=11800, name= "walking, 3.0 mph, moderately and carrying light objects less than 25 lbs", METS= 4.5).save()
    PhysicalActivity(id=11805, name= "walking, pushing a wheelchair", METS= 3.5).save()
    PhysicalActivity(id=11810, name= "walking, 3.5 mph, briskly and carrying objects less than 25 lbs", METS= 4.8).save()
    PhysicalActivity(id=11820, name= "walking or walk downstairs or standing, carrying objects about 25 to 49 lbs", METS= 5.0).save()
    PhysicalActivity(id=11830, name= "walking or walk downstairs or standing, carrying objects about 50 to 74 lbs", METS= 6.5).save()
    PhysicalActivity(id=11840, name= "walking or walk downstairs or standing, carrying objects about 75 to 99 lbs", METS= 7.5).save()
    PhysicalActivity(id=11850, name= "walking or walk downstairs or standing, carrying objects about 100 lbs or more", METS= 8.5).save()
    PhysicalActivity(id=11870, name= "working in scene shop, theater actor, backstage employee", METS= 3.0).save()
    PhysicalActivity(id=12010, name= "jog/walk combination (jogging component of less than 10 minutes) (Taylor Code 180)", METS= 6.0).save()
    PhysicalActivity(id=12020, name= "jogging, general", METS= 7.0).save()
    PhysicalActivity(id=12025, name= "jogging, in place", METS= 8.0).save()
    PhysicalActivity(id=12027, name= "jogging, on a mini-tramp", METS= 4.5).save()
    PhysicalActivity(id=12029, name= "Running, 4 mph (13 min/mile)", METS= 6.0).save()
    PhysicalActivity(id=12030, name= "running, 5 mph (12 min/mile)", METS= 8.3).save()
    PhysicalActivity(id=12040, name= "running, 5.2 mph (11.5 min/mile)", METS= 9.0).save()
    PhysicalActivity(id=12050, name= "running, 6 mph (10 min/mile)", METS= 9.8).save()
    PhysicalActivity(id=12060, name= "running, 6.7 mph (9 min/mile)", METS= 10.5).save()
    PhysicalActivity(id=12070, name= "running, 7 mph (8.5 min/mile)", METS= 11.0).save()
    PhysicalActivity(id=12080, name= "running, 7.5 mph (8 min/mile)", METS= 11.5).save()
    PhysicalActivity(id=12090, name= "running, 8 mph (7.5 min/mile)", METS= 11.8).save()
    PhysicalActivity(id=12100, name= "running, 8.6 mph (7 min/mile)", METS= 12.3).save()
    PhysicalActivity(id=12110, name= "running, 9 mph (6.5 min/mile)", METS= 12.8).save()
    PhysicalActivity(id=12120, name= "running, 10 mph (6 min/mile)", METS= 14.5).save()
    PhysicalActivity(id=12130, name= "running, 11 mph (5.5 min/mile)", METS= 16.0).save()
    PhysicalActivity(id=12132, name= "running, 12 mph (5 min/mile)", METS= 19.0).save()
    PhysicalActivity(id=12134, name= "running, 13 mph (4.6 min/mile)", METS= 19.8).save()
    PhysicalActivity(id=12135, name= "running, 14 mph (4.3 min/mile)", METS= 23.0).save()
    PhysicalActivity(id=12140, name= "running, cross country", METS= 9.0).save()
    PhysicalActivity(id=12150, name= "running, (Taylor code 200)", METS= 8.0).save()
    PhysicalActivity(id=12170, name= "running, stairs, up", METS= 15.0).save()
    PhysicalActivity(id=12180, name= "running, on a track, team practice", METS= 10.0).save()
    PhysicalActivity(id=12190, name= "running, training, pushing a wheelchair or baby carrier", METS= 8.0).save()
    PhysicalActivity(id=12200, name= "running, marathon", METS= 13.3).save()
    PhysicalActivity(id=13000, name= "getting ready for bed, general, standing", METS= 2.3).save()
    PhysicalActivity(id=13009, name= "sitting on toilet, eliminating while standing or squating", METS= 1.8).save()
    PhysicalActivity(id=13010, name= "bathing, sitting", METS= 1.5).save()
    PhysicalActivity(id=13020, name= "dressing, undressing, standing or sitting", METS= 2.5).save()
    PhysicalActivity(id=13030, name= "eating, sitting", METS= 1.5).save()
    PhysicalActivity(id=13035, name= "talking and eating or eating only, standing", METS= 2.0).save()
    PhysicalActivity(id=13036, name= "taking medication, sitting or standing", METS= 1.5).save()
    PhysicalActivity(id=13040, name= "grooming, washing hands, shaving, brushing teeth, putting on make-up, sitting or standing", METS= 2.0).save()
    PhysicalActivity(id=13045, name= "hairstyling, standing", METS= 2.5).save()
    PhysicalActivity(id=13046, name= "having hair or nails done by someone else, sitting", METS= 1.3).save()
    PhysicalActivity(id=13050, name= "showering, toweling off, standing", METS= 2.0).save()
    PhysicalActivity(id=14010, name= "active, vigorous effort", METS= 2.8).save()
    PhysicalActivity(id=14020, name= "general, moderate effort", METS= 1.8).save()
    PhysicalActivity(id=14030, name= "passive, light effort, kissing, hugging", METS= 1.3).save()
    PhysicalActivity(id=15000, name= "Alaska Native Games, Eskimo Olympics, general", METS= 5.5).save()
    PhysicalActivity(id=15010, name= "archery, non-hunting", METS= 4.3).save()
    PhysicalActivity(id=15020, name= "badminton, competitive (Taylor Code 450)", METS= 7.0).save()
    PhysicalActivity(id=15030, name= "badminton, social singles and doubles, general", METS= 5.5).save()
    PhysicalActivity(id=15040, name= "basketball, game (Taylor Code 490)", METS= 8.0).save()
    PhysicalActivity(id=15050, name= "basketball, non-game, general (Taylor Code 480)", METS= 6.0).save()
    PhysicalActivity(id=15055, name= "basketball, general", METS= 6.5).save()
    PhysicalActivity(id=15060, name= "basketball, officiating (Taylor Code 500)", METS= 7.0).save()
    PhysicalActivity(id=15070, name= "basketball, shooting baskets", METS= 4.5).save()
    PhysicalActivity(id=15072, name= "basketball, drills, practice", METS= 9.3).save()
    PhysicalActivity(id=15075, name= "basketball, wheelchair", METS= 7.8).save()
    PhysicalActivity(id=15080, name= "billiards", METS= 2.5).save()
    PhysicalActivity(id=15090, name= "bowling (Taylor Code 390)", METS= 3.0).save()
    PhysicalActivity(id=15092, name= "bowling, indoor, bowling alley", METS= 3.8).save()
    PhysicalActivity(id=15100, name= "boxing, in ring, general", METS= 12.8).save()
    PhysicalActivity(id=15110, name= "boxing, punching bag", METS= 5.5).save()
    PhysicalActivity(id=15120, name= "boxing, sparring", METS= 7.8).save()
    PhysicalActivity(id=15130, name= "broomball", METS= 7.0).save()
    PhysicalActivity(id=15135, name= "children\u2019s games, adults playing (e.g., hopscotch, 4-square, dodgeball, playground apparatus, t-ball, tetherball, marbles, arcade games), moderate effort", METS= 5.8).save()
    PhysicalActivity(id=15138, name= "cheerleading, gymnastic moves, competitive", METS= 6.0).save()
    PhysicalActivity(id=15140, name= "coaching, football, soccer, basketball, baseball, swimming, etc.", METS= 4.0).save()
    PhysicalActivity(id=15142, name= "coaching, actively playing sport with players", METS= 8.0).save()
    PhysicalActivity(id=15150, name= "cricket, batting, bowling, fielding", METS= 4.8).save()
    PhysicalActivity(id=15160, name= "croquet", METS= 3.3).save()
    PhysicalActivity(id=15170, name= "curling", METS= 4.0).save()
    PhysicalActivity(id=15180, name= "darts, wall or lawn", METS= 2.5).save()
    PhysicalActivity(id=15190, name= "drag racing, pushing or driving a car", METS= 6.0).save()
    PhysicalActivity(id=15192, name= "auto racing, open wheel", METS= 8.5).save()
    PhysicalActivity(id=15200, name= "fencing", METS= 6.0).save()
    PhysicalActivity(id=15210, name= "football, competitive", METS= 8.0).save()
    PhysicalActivity(id=15230, name= "football, touch, flag, general (Taylor Code 510)", METS= 8.0).save()
    PhysicalActivity(id=15232, name= "football, touch, flag, light effort", METS= 4.0).save()
    PhysicalActivity(id=15235, name= "football or baseball, playing catch", METS= 2.5).save()
    PhysicalActivity(id=15240, name= "frisbee playing, general", METS= 3.0).save()
    PhysicalActivity(id=15250, name= "frisbee, ultimate", METS= 8.0).save()
    PhysicalActivity(id=15255, name= "golf, general", METS= 4.8).save()
    PhysicalActivity(id=15265, name= "golf, walking, carrying clubs", METS= 4.3).save()
    PhysicalActivity(id=15270, name= "golf, miniature, driving range", METS= 3.0).save()
    PhysicalActivity(id=15285, name= "golf, walking, pulling clubs", METS= 5.3).save()
    PhysicalActivity(id=15290, name= "golf, using power cart (Taylor Code 070)", METS= 3.5).save()
    PhysicalActivity(id=15300, name= "gymnastics, general", METS= 3.8).save()
    PhysicalActivity(id=15310, name= "hacky sack", METS= 4.0).save()
    PhysicalActivity(id=15320, name= "handball, general (Taylor Code 520)", METS= 12.0).save()
    PhysicalActivity(id=15330, name= "handball, team", METS= 8.0).save()
    PhysicalActivity(id=15335, name= "high ropes course, multiple elements", METS= 4.0).save()
    PhysicalActivity(id=15340, name= "hang gliding", METS= 3.5).save()
    PhysicalActivity(id=15350, name= "hockey, field", METS= 7.8).save()
    PhysicalActivity(id=15360, name= "hockey, ice, general", METS= 8.0).save()
    PhysicalActivity(id=15362, name= "hockey, ice, competitive", METS= 10.0).save()
    PhysicalActivity(id=15370, name= "horseback riding, general", METS= 5.5).save()
    PhysicalActivity(id=15375, name= "horse chores, feeding, watering, cleaning stalls, implied walking and lifting loads", METS= 4.3).save()
    PhysicalActivity(id=15380, name= "saddling, cleaning, grooming, harnessing and unharnessing horse", METS= 4.5).save()
    PhysicalActivity(id=15390, name= "horseback riding, trotting", METS= 5.8).save()
    PhysicalActivity(id=15395, name= "horseback riding, canter or gallop", METS= 7.3).save()
    PhysicalActivity(id=15400, name= "horseback riding,walking", METS= 3.8).save()
    PhysicalActivity(id=15402, name= "horseback riding, jumping", METS= 9.0).save()
    PhysicalActivity(id=15408, name= "horse cart, driving, standing or sitting", METS= 1.8).save()
    PhysicalActivity(id=15410, name= "horseshoe pitching, quoits", METS= 3.0).save()
    PhysicalActivity(id=15420, name= "jai alai", METS= 12.0).save()
    PhysicalActivity(id=15425, name= "martial arts, different types, slower pace, novice performers, practice", METS= 5.3).save()
    PhysicalActivity(id=15430, name= "martial arts, different types, moderate pace (e.g., judo, jujitsu, karate, kick boxing, tae kwan do, tai-bo, Muay Thai boxing)", METS= 10.3).save()
    PhysicalActivity(id=15440, name= "juggling", METS= 4.0).save()
    PhysicalActivity(id=15450, name= "kickball", METS= 7.0).save()
    PhysicalActivity(id=15460, name= "lacrosse", METS= 8.0).save()
    PhysicalActivity(id=15465, name= "lawn bowling, bocce ball, outdoor", METS= 3.3).save()
    PhysicalActivity(id=15470, name= "moto-cross, off-road motor sports, all-terrain vehicle, general", METS= 4.0).save()
    PhysicalActivity(id=15480, name= "orienteering", METS= 9.0).save()
    PhysicalActivity(id=15490, name= "paddleball, competitive", METS= 10.0).save()
    PhysicalActivity(id=15500, name= "paddleball, casual, general (Taylor Code 460)", METS= 6.0).save()
    PhysicalActivity(id=15510, name= "polo, on horseback", METS= 8.0).save()
    PhysicalActivity(id=15520, name= "racquetball, competitive", METS= 10.0).save()
    PhysicalActivity(id=15530, name= "racquetball, general (Taylor Code 470)", METS= 7.0).save()
    PhysicalActivity(id=15533, name= "rock or mountain climbing (Taylor Code 470) (Formerly code = 17120)", METS= 8.0).save()
    PhysicalActivity(id=15535, name= "rock climbing, ascending rock, high difficulty", METS= 7.5).save()
    PhysicalActivity(id=15537, name= "rock climbing, ascending or traversing rock, low-to-moderate difficulty", METS= 5.8).save()
    PhysicalActivity(id=15540, name= "rock climbing, rappelling", METS= 5.0).save()
    PhysicalActivity(id=15542, name= "rodeo sports, general, light effort", METS= 4.0).save()
    PhysicalActivity(id=15544, name= "rodeo sports, general, moderate effort", METS= 5.5).save()
    PhysicalActivity(id=15546, name= "rodeo sports, general, vigorous effort", METS= 7.0).save()
    PhysicalActivity(id=15550, name= "rope jumping, fast pace, 120-160 skips/min", METS= 12.3).save()
    PhysicalActivity(id=15551, name= "rope jumping, moderate pace, 100-120 skips/min, general, 2 foot skip, plain bounce", METS= 11.8).save()
    PhysicalActivity(id=15552, name= "rope jumping, slow pace, < 100 skips/min, 2 foot skip, rhythm bounce", METS= 8.8).save()
    PhysicalActivity(id=15560, name= "rugby, union, team, competitive", METS= 8.3).save()
    PhysicalActivity(id=15562, name= "rugby, touch, non-competitive", METS= 6.3).save()
    PhysicalActivity(id=15570, name= "shuffleboard", METS= 3.0).save()
    PhysicalActivity(id=15580, name= "skateboarding, general, moderate effort", METS= 5.0).save()
    PhysicalActivity(id=15582, name= "skateboarding, competitive, vigorous effort", METS= 6.0).save()
    PhysicalActivity(id=15590, name= "skating, roller (Taylor Code 360)", METS= 7.0).save()
    PhysicalActivity(id=15591, name= "rollerblading, in-line skating, 14.4 km/h (9.0 mph), recreational pace", METS= 7.5).save()
    PhysicalActivity(id=15592, name= "rollerblading, in-line skating, 17.7 km/h (11.0 mph), moderate pace, exercise training", METS= 9.8).save()
    PhysicalActivity(id=15593, name= "rollerblading, in-line skating, 21.0 to 21.7 km/h (13.0 to 13.6 mph), fast pace, exercise training", METS= 12.3).save()
    PhysicalActivity(id=15594, name= "rollerblading, in-line skating, 24.0 km/h (15.0 mph), maximal effort", METS= 14.0).save()
    PhysicalActivity(id=15600, name= "skydiving, base jumping, bungee jumping", METS= 3.5).save()
    PhysicalActivity(id=15605, name= "soccer, competitive", METS= 10.0).save()
    PhysicalActivity(id=15610, name= "soccer, casual, general (Taylor Code 540)", METS= 7.0).save()
    PhysicalActivity(id=15620, name= "softball or baseball, fast or slow pitch, general (Taylor Code 440)", METS= 5.0).save()
    PhysicalActivity(id=15625, name= "softball, practice", METS= 4.0).save()
    PhysicalActivity(id=15630, name= "softball, officiating", METS= 4.0).save()
    PhysicalActivity(id=15640, name= "softball,pitching", METS= 6.0).save()
    PhysicalActivity(id=15645, name= "sports spectator, very excited, emotional, physically moving", METS= 3.3).save()
    PhysicalActivity(id=15650, name= "squash (Taylor Code 530)", METS= 12.0).save()
    PhysicalActivity(id=15652, name= "squash, general", METS= 7.3).save()
    PhysicalActivity(id=15660, name= "table tennis, ping pong (Taylor Code 410)", METS= 4.0).save()
    PhysicalActivity(id=15670, name= "tai chi, qi gong, general", METS= 3.0).save()
    PhysicalActivity(id=15672, name= "tai chi, qi gong, sitting, light effort", METS= 1.5).save()
    PhysicalActivity(id=15675, name= "tennis, general", METS= 7.3).save()
    PhysicalActivity(id=15680, name= "tennis, doubles (Taylor Code 430)", METS= 6.0).save()
    PhysicalActivity(id=15685, name= "tennis, doubles", METS= 4.5).save()
    PhysicalActivity(id=15690, name= "tennis, singles (Taylor Code 420)", METS= 8.0).save()
    PhysicalActivity(id=15695, name= "tennis, hitting balls, non-game play, moderate effort", METS= 5.0).save()
    PhysicalActivity(id=15700, name= "trampoline, recreational", METS= 3.5).save()
    PhysicalActivity(id=15702, name= "trampoline, competitive", METS= 4.5).save()
    PhysicalActivity(id=15710, name= "volleyball (Taylor Code 400)", METS= 4.0).save()
    PhysicalActivity(id=15711, name= "volleyball, competitive, in gymnasium", METS= 6.0).save()
    PhysicalActivity(id=15720, name= "volleyball, non-competitive, 6 - 9 member team, general", METS= 3.0).save()
    PhysicalActivity(id=15725, name= "volleyball, beach, in sand", METS= 8.0).save()
    PhysicalActivity(id=15730, name= "wrestling (one match = 5 minutes)", METS= 6.0).save()
    PhysicalActivity(id=15731, name= "wallyball, general", METS= 7.0).save()
    PhysicalActivity(id=15732, name= "track and field (e.g., shot, discus, hammer throw)", METS= 4.0).save()
    PhysicalActivity(id=15733, name= "track and field (e.g., high jump, long jump, triple jump, javelin, pole vault)", METS= 6.0).save()
    PhysicalActivity(id=15734, name= "track and field (e.g., steeplechase, hurdles)", METS= 10.0).save()
    PhysicalActivity(id=16010, name= "automobile or light truck (not a semi) driving", METS= 2.5).save()
    PhysicalActivity(id=16015, name= "riding in a car or truck", METS= 1.3).save()
    PhysicalActivity(id=16016, name= "riding in a bus or train", METS= 1.3).save()
    PhysicalActivity(id=16020, name= "flying airplane or helicopter", METS= 1.8).save()
    PhysicalActivity(id=16030, name= "motor scooter, motorcycle", METS= 3.5).save()
    PhysicalActivity(id=16035, name= "pulling rickshaw", METS= 6.3).save()
    PhysicalActivity(id=16040, name= "pushing plane in and out of hangar", METS= 6.0).save()
    PhysicalActivity(id=16050, name= "truck, semi, tractor, > 1 ton, or bus, driving", METS= 2.5).save()
    PhysicalActivity(id=16060, name= "walking for transportation, 2.8-3.2 mph, level, moderate pace, firm surface", METS= 3.5).save()
    PhysicalActivity(id=17010, name= "backpacking (Taylor Code 050)", METS= 7.0).save()
    PhysicalActivity(id=17012, name= "backpacking, hiking or organized walking with a daypack", METS= 7.8).save()
    PhysicalActivity(id=17020, name= "carrying 15 pound load (e.g. suitcase), level ground or downstairs", METS= 5.0).save()
    PhysicalActivity(id=17021, name= "carrying 15 lb child, slow walking", METS= 2.3).save()
    PhysicalActivity(id=17025, name= "carrying load upstairs, general", METS= 8.3).save()
    PhysicalActivity(id=17026, name= "carrying 1 to 15 lb load, upstairs", METS= 5.0).save()
    PhysicalActivity(id=17027, name= "carrying 16 to 24 lb load, upstairs", METS= 6.0).save()
    PhysicalActivity(id=17028, name= "carrying 25 to 49 lb load, upstairs", METS= 8.0).save()
    PhysicalActivity(id=17029, name= "carrying 50 to 74 lb load, upstairs", METS= 10.0).save()
    PhysicalActivity(id=17030, name= "carrying > 74 lb load, upstairs", METS= 12.0).save()
    PhysicalActivity(id=17031, name= "loading /unloading a car, implied walking", METS= 3.5).save()
    PhysicalActivity(id=17033, name= "climbing hills, no load", METS= 6.3).save()
    PhysicalActivity(id=17035, name= "climbing hills with 0 to 9 lb load", METS= 6.5).save()
    PhysicalActivity(id=17040, name= "climbing hills with 10 to 20 lb load", METS= 7.3).save()
    PhysicalActivity(id=17050, name= "climbing hills with 21 to 42 lb load", METS= 8.3).save()
    PhysicalActivity(id=17060, name= "climbing hills with 42+ lb load", METS= 9.0).save()
    PhysicalActivity(id=17070, name= "descending stairs", METS= 3.5).save()
    PhysicalActivity(id=17080, name= "hiking, cross country (Taylor Code 040)", METS= 6.0).save()
    PhysicalActivity(id=17082, name= "hiking or walking at a normal pace through fields and hillsides", METS= 5.3).save()
    PhysicalActivity(id=17085, name= "bird watching, slow walk", METS= 2.5).save()
    PhysicalActivity(id=17088, name= "marching, moderate speed, military, no pack", METS= 4.5).save()
    PhysicalActivity(id=17090, name= "marching rapidly, military, no pack", METS= 8.0).save()
    PhysicalActivity(id=17100, name= "pushing or pulling stroller with child or walking with children, 2.5 to 3.1 mph", METS= 4.0).save()
    PhysicalActivity(id=17105, name= "pushing a wheelchair, non-occupational", METS= 3.8).save()
    PhysicalActivity(id=17110, name= "race walking", METS= 6.5).save()
    PhysicalActivity(id=17130, name= "stair climbing, using or climbing up ladder (Taylor Code 030)", METS= 8.0).save()
    PhysicalActivity(id=17133, name= "stair climbing, slow pace", METS= 4.0).save()
    PhysicalActivity(id=17134, name= "stair climbing, fast pace", METS= 8.8).save()
    PhysicalActivity(id=17140, name= "using crutches", METS= 5.0).save()
    PhysicalActivity(id=17150, name= "walking, household", METS= 2.0).save()
    PhysicalActivity(id=17151, name= "walking, less than 2.0 mph, level, strolling, very slow", METS= 2.0).save()
    PhysicalActivity(id=17152, name= "walking, 2.0 mph, level, slow pace, firm surface", METS= 2.8).save()
    PhysicalActivity(id=17160, name= "walking for pleasure (Taylor Code 010)", METS= 3.5).save()
    PhysicalActivity(id=17161, name= "walking from house to car or bus, from car or bus to go places, from car or bus to and from the worksite", METS= 2.5).save()
    PhysicalActivity(id=17162, name= "walking to neighbor\u2019s house or family\u2019s house for social reasons", METS= 2.5).save()
    PhysicalActivity(id=17165, name= "walking the dog", METS= 3.0).save()
    PhysicalActivity(id=17170, name= "walking, 2.5 mph, level, firm surface", METS= 3.0).save()
    PhysicalActivity(id=17180, name= "walking, 2.5 mph, downhill", METS= 3.3).save()
    PhysicalActivity(id=17190, name= "walking, 2.8 to 3.2 mph, level, moderate pace, firm surface", METS= 3.5).save()
    PhysicalActivity(id=17200, name= "walking, 3.5 mph, level, brisk, firm surface, walking for exercise", METS= 4.3).save()
    PhysicalActivity(id=17210, name= "walking, 2.9 to 3.5 mph, uphill, 1 to 5% grade", METS= 5.3).save()
    PhysicalActivity(id=17211, name= "walking, 2.9 to 3.5 mph, uphill, 6% to 15% grade", METS= 8.0).save()
    PhysicalActivity(id=17220, name= "walking, 4.0 mph, level, firm surface, very brisk pace", METS= 5.0).save()
    PhysicalActivity(id=17230, name= "walking, 4.5 mph, level, firm surface, very, very brisk", METS= 7.0).save()
    PhysicalActivity(id=17231, name= "walking, 5.0 mph, level, firm surface", METS= 8.3).save()
    PhysicalActivity(id=17235, name= "walking, 5.0 mph, uphill, 3% grade", METS= 9.8).save()
    PhysicalActivity(id=17250, name= "walking, for pleasure, work break", METS= 3.5).save()
    PhysicalActivity(id=17260, name= "walking, grass track", METS= 4.8).save()
    PhysicalActivity(id=17262, name= "walking, normal pace, plowed field or sand", METS= 4.5).save()
    PhysicalActivity(id=17270, name= "walking, to work or class (Taylor Code 015)", METS= 4.0).save()
    PhysicalActivity(id=17280, name= "walking, to and from an outhouse", METS= 2.5).save()
    PhysicalActivity(id=17302, name= "walking, for exercise, 3.5 to 4 mph, with ski poles, Nordic walking, level, moderate pace", METS= 4.8).save()
    PhysicalActivity(id=17305, name= "walking, for exercise, 5.0 mph, with ski poles, Nordic walking, level, fast pace", METS= 9.5).save()
    PhysicalActivity(id=17310, name= "walking, for exercise, with ski poles, Nordic walking, uphill", METS= 6.8).save()
    PhysicalActivity(id=17320, name= "walking, backwards, 3.5 mph, level", METS= 6.0).save()
    PhysicalActivity(id=17325, name= "walking, backwards, 3.5 mph, uphill, 5% grade", METS= 8.0).save()
    PhysicalActivity(id=18010, name= "boating, power, driving", METS= 2.5).save()
    PhysicalActivity(id=18012, name= "boating, power, passenger, light", METS= 1.3).save()
    PhysicalActivity(id=18020, name= "canoeing, on camping trip (Taylor Code 270)", METS= 4.0).save()
    PhysicalActivity(id=18025, name= "canoeing, harvesting wild rice, knocking rice off the stalks", METS= 3.3).save()
    PhysicalActivity(id=18030, name= "canoeing, portaging", METS= 7.0).save()
    PhysicalActivity(id=18040, name= "canoeing, rowing, 2.0-3.9 mph, light effort", METS= 2.8).save()
    PhysicalActivity(id=18050, name= "canoeing, rowing, 4.0-5.9 mph, moderate effort", METS= 5.8).save()
    PhysicalActivity(id=18060, name= "canoeing, rowing, kayaking, competition, >6 mph, vigorous effort", METS= 12.5).save()
    PhysicalActivity(id=18070, name= "canoeing, rowing, for pleasure, general (Taylor Code 250)", METS= 3.5).save()
    PhysicalActivity(id=18080, name= "canoeing, rowing, in competition, or crew or sculling (Taylor Code 260)", METS= 12.0).save()
    PhysicalActivity(id=18090, name= "diving, springboard or platform", METS= 3.0).save()
    PhysicalActivity(id=18100, name= "kayaking, moderate effort", METS= 5.0).save()
    PhysicalActivity(id=18110, name= "paddle boat", METS= 4.0).save()
    PhysicalActivity(id=18120, name= "sailing, boat and board sailing, windsurfing, ice sailing, general (Taylor Code 235)", METS= 3.0).save()
    PhysicalActivity(id=18130, name= "sailing, in competition", METS= 4.5).save()
    PhysicalActivity(id=18140, name= "sailing, Sunfish/Laser/Hobby Cat, Keel boats, ocean sailing, yachting, leisure", METS= 3.3).save()
    PhysicalActivity(id=18150, name= "skiing, water or wakeboarding (Taylor Code 220)", METS= 6.0).save()
    PhysicalActivity(id=18160, name= "jet skiing, driving, in water", METS= 7.0).save()
    PhysicalActivity(id=18180, name= "skindiving, fast", METS= 15.8).save()
    PhysicalActivity(id=18190, name= "skindiving, moderate", METS= 11.8).save()
    PhysicalActivity(id=18200, name= "skindiving, scuba diving, general (Taylor Code 310)", METS= 7.0).save()
    PhysicalActivity(id=18210, name= "snorkeling (Taylor Code 310)", METS= 5.0).save()
    PhysicalActivity(id=18220, name= "surfing, body or board, general", METS= 3.0).save()
    PhysicalActivity(id=18222, name= "surfing, body or board, competitive", METS= 5.0).save()
    PhysicalActivity(id=18225, name= "paddle boarding, standing", METS= 6.0).save()
    PhysicalActivity(id=18230, name= "swimming laps, freestyle, fast, vigorous effort", METS= 9.8).save()
    PhysicalActivity(id=18240, name= "swimming laps, freestyle, front crawl, slow, light or moderate effort", METS= 5.8).save()
    PhysicalActivity(id=18250, name= "swimming, backstroke, general, training or competition", METS= 9.5).save()
    PhysicalActivity(id=18255, name= "swimming, backstroke, recreational", METS= 4.8).save()
    PhysicalActivity(id=18260, name= "swimming, breaststroke, general, training or competition", METS= 10.3).save()
    PhysicalActivity(id=18265, name= "swimming, breaststroke, recreational", METS= 5.3).save()
    PhysicalActivity(id=18270, name= "swimming, butterfly, general", METS= 13.8).save()
    PhysicalActivity(id=18280, name= "swimming, crawl, fast speed, ~75 yards/minute, vigorous effort", METS= 10.0).save()
    PhysicalActivity(id=18290, name= "swimming, crawl, medium speed, ~50 yards/minute, vigorous effort", METS= 8.3).save()
    PhysicalActivity(id=18300, name= "swimming, lake, ocean, river (Taylor Codes 280, 295)", METS= 6.0).save()
    PhysicalActivity(id=18310, name= "swimming, leisurely, not lap swimming, general", METS= 6.0).save()
    PhysicalActivity(id=18320, name= "swimming, sidestroke, general", METS= 7.0).save()
    PhysicalActivity(id=18330, name= "swimming, synchronized", METS= 8.0).save()
    PhysicalActivity(id=18340, name= "swimming, treading water, fast, vigorous effort", METS= 9.8).save()
    PhysicalActivity(id=18350, name= "swimming, treading water, moderate effort, general", METS= 3.5).save()
    PhysicalActivity(id=18352, name= "tubing, floating on a river, general", METS= 2.3).save()
    PhysicalActivity(id=18355, name= "water aerobics, water calisthenics", METS= 5.5).save()
    PhysicalActivity(id=18360, name= "water polo", METS= 10.0).save()
    PhysicalActivity(id=18365, name= "water volleyball", METS= 3.0).save()
    PhysicalActivity(id=18366, name= "water jogging", METS= 9.8).save()
    PhysicalActivity(id=18367, name= "water walking, light effort, slow pace", METS= 2.5).save()
    PhysicalActivity(id=18368, name= "water walking, moderate effort, moderate pace", METS= 4.5).save()
    PhysicalActivity(id=18369, name= "water walking, vigorous effort, brisk pace", METS= 6.8).save()
    PhysicalActivity(id=18370, name= "whitewater rafting, kayaking, or canoeing", METS= 5.0).save()
    PhysicalActivity(id=18380, name= "windsurfing, not pumping for speed", METS= 5.0).save()
    PhysicalActivity(id=18385, name= "windsurfing or kitesurfing, crossing trial", METS= 11.0).save()
    PhysicalActivity(id=18390, name= "windsurfing, competition, pumping for speed", METS= 13.5).save()
    PhysicalActivity(id=19005, name= "dog sledding, mushing", METS= 7.5).save()
    PhysicalActivity(id=19006, name= "dog sledding, passenger", METS= 2.5).save()
    PhysicalActivity(id=19010, name= "moving ice house, set up/drill holes", METS= 6.0).save()
    PhysicalActivity(id=19011, name= "ice fishing, sitting", METS= 2.0).save()
    PhysicalActivity(id=19018, name= "skating, ice dancing", METS= 14.0).save()
    PhysicalActivity(id=19020, name= "skating, ice, 9 mph or less", METS= 5.5).save()
    PhysicalActivity(id=19030, name= "skating, ice, general (Taylor Code 360)", METS= 7.0).save()
    PhysicalActivity(id=19040, name= "skating, ice, rapidly, more than 9 mph, not competitive", METS= 9.0).save()
    PhysicalActivity(id=19050, name= "skating, speed, competitive", METS= 13.3).save()
    PhysicalActivity(id=19060, name= "ski jumping, climb up carrying skis", METS= 7.0).save()
    PhysicalActivity(id=19075, name= "skiing, general", METS= 7.0).save()
    PhysicalActivity(id=19080, name= "skiing, cross country, 2.5 mph, slow or light effort, ski walking", METS= 6.8).save()
    PhysicalActivity(id=19090, name= "skiing, cross country, 4.0-4.9 mph, moderate speed and effort, general", METS= 9.0).save()
    PhysicalActivity(id=19100, name= "skiing, cross country, 5.0-7.9 mph, brisk speed, vigorous effort", METS= 12.5).save()
    PhysicalActivity(id=19110, name= "skiing, cross country, >8.0 mph, elite skier, racing", METS= 15.0).save()
    PhysicalActivity(id=19130, name= "skiing, cross country, hard snow, uphill, maximum, snow mountaineering", METS= 15.5).save()
    PhysicalActivity(id=19135, name= "skiing, cross-country, skating", METS= 13.3).save()
    PhysicalActivity(id=19140, name= "skiing, cross-country, biathlon, skating technique", METS= 13.5).save()
    PhysicalActivity(id=19150, name= "skiing, downhill, alpine or snowboarding, light effort, active time only", METS= 4.3).save()
    PhysicalActivity(id=19160, name= "skiing, downhill, alpine or snowboarding, moderate effort, general, active time only", METS= 5.3).save()
    PhysicalActivity(id=19170, name= "skiing, downhill, vigorous effort, racing", METS= 8.0).save()
    PhysicalActivity(id=19175, name= "skiing, roller, elite racers", METS= 12.5).save()
    PhysicalActivity(id=19180, name= "sledding, tobogganing, bobsledding, luge (Taylor Code 370)", METS= 7.0).save()
    PhysicalActivity(id=19190, name= "snow shoeing, moderate effort", METS= 5.3).save()
    PhysicalActivity(id=19192, name= "snow shoeing, vigorous effort", METS= 10.0).save()
    PhysicalActivity(id=19200, name= "snowmobiling, driving, moderate", METS= 3.5).save()
    PhysicalActivity(id=19202, name= "snowmobiling, passenger", METS= 2.0).save()
    PhysicalActivity(id=19252, name= "snow shoveling, by hand, moderate effort", METS= 5.3).save()
    PhysicalActivity(id=19254, name= "snow shoveling, by hand, vigorous effort", METS= 7.5).save()
    PhysicalActivity(id=19260, name= "snow blower, walking and pushing", METS= 2.5).save()
    PhysicalActivity(id=20000, name= "sitting in church, in service, attending a ceremony, sitting quietly", METS= 1.3).save()
    PhysicalActivity(id=20001, name= "sitting, playing an instrument at church", METS= 2.0).save()
    PhysicalActivity(id=20005, name= "sitting in church, talking or singing, attending a ceremony, sitting, active participation", METS= 1.8).save()
    PhysicalActivity(id=20010, name= "sitting, reading religious materials at home", METS= 1.3).save()
    PhysicalActivity(id=20015, name= "standing quietly in church, attending a ceremony", METS= 1.3).save()
    PhysicalActivity(id=20020, name= "standing, singing in church, attending a ceremony, standing, active participation", METS= 2.0).save()
    PhysicalActivity(id=20025, name= "kneeling in church or at home, praying", METS= 1.3).save()
    PhysicalActivity(id=20030, name= "standing, talking in church", METS= 1.8).save()
    PhysicalActivity(id=20035, name= "walking in church", METS= 2.0).save()
    PhysicalActivity(id=20036, name= "walking, less than 2.0 mph, very slow", METS= 2.0).save()
    PhysicalActivity(id=20037, name= "walking, 3.0 mph, moderate speed, not carrying anything", METS= 3.5).save()
    PhysicalActivity(id=20038, name= "walking, 3.5 mph, brisk speed, not carrying anything", METS= 4.3).save()
    PhysicalActivity(id=20039, name= "walk/stand combination for religious purposes, usher", METS= 2.0).save()
    PhysicalActivity(id=20040, name= "praise with dance or run, spiritual dancing in church", METS= 5.0).save()
    PhysicalActivity(id=20045, name= "serving food at church", METS= 2.5).save()
    PhysicalActivity(id=20046, name= "preparing food at church", METS= 2.0).save()
    PhysicalActivity(id=20047, name= "washing dishes, cleaning kitchen at church", METS= 3.3).save()
    PhysicalActivity(id=20050, name= "eating at church", METS= 1.5).save()
    PhysicalActivity(id=20055, name= "eating/talking at church or standing eating, American Indian Feast days", METS= 2.0).save()
    PhysicalActivity(id=20060, name= "cleaning church", METS= 3.3).save()
    PhysicalActivity(id=20061, name= "general yard work at church", METS= 4.0).save()
    PhysicalActivity(id=20065, name= "standing, moderate effort (e.g., lifting heavy objects, assembling at fast rate)", METS= 3.5).save()
    PhysicalActivity(id=20095, name= "Standing, moderate-to-heavy effort, manual labor, lifting ? 50 lbs, heavy maintenance", METS= 4.5).save()
    PhysicalActivity(id=20100, name= "typing, electric, manual, or computer", METS= 1.3).save()
    PhysicalActivity(id=21000, name= "sitting, meeting, general, and/or with talking involved", METS= 1.5).save()
    PhysicalActivity(id=21005, name= "sitting, light office work, in general", METS= 1.5).save()
    PhysicalActivity(id=21010, name= "sitting, moderate work", METS= 2.5).save()
    PhysicalActivity(id=21015, name= "standing, light work (filing, talking, assembling)", METS= 2.3).save()
    PhysicalActivity(id=21016, name= "sitting, child care, only active periods", METS= 2.0).save()
    PhysicalActivity(id=21017, name= "standing, child care, only active periods", METS= 3.0).save()
    PhysicalActivity(id=21018, name= "walk/run play with children, moderate, only active periods", METS= 3.5).save()
    PhysicalActivity(id=21019, name= "walk/run play with children, vigorous, only active periods", METS= 5.8).save()
    PhysicalActivity(id=21020, name= "standing, light/moderate work (e.g., pack boxes, assemble/repair, set up chairs/furniture)", METS= 3.0).save()
    PhysicalActivity(id=21025, name= "standing, moderate (lifting 50 lbs., assembling at fast rate)", METS= 3.5).save()
    PhysicalActivity(id=21030, name= "standing, moderate/heavy work", METS= 4.5).save()
    PhysicalActivity(id=21035, name= "typing, electric, manual, or computer", METS= 1.3).save()
    PhysicalActivity(id=21040, name= "walking, less than 2.0 mph, very slow", METS= 2.0).save()
    PhysicalActivity(id=21045, name= "walking, 3.0 mph, moderate speed, not carrying anything", METS= 3.5).save()
    PhysicalActivity(id=21050, name= "walking, 3.5 mph, brisk speed, not carrying anything", METS= 4.3).save()
    PhysicalActivity(id=21055, name= "walking, 2.5 mph slowly and carrying objects less than 25 lbs", METS= 3.5).save()
    PhysicalActivity(id=21060, name= "walking, 3.0 mph moderately and carrying objects less than 25 lbs, pushing something", METS= 4.5).save()
    PhysicalActivity(id=21065, name= "walking, 3.5 mph, briskly and carrying objects less than 25 lbs", METS= 4.8).save()
    PhysicalActivity(id=21070, name= "walk/stand combination, for volunteer purposes", METS= 3.0).save()
